import type { Metadata } from 'next';
import './globals.css';
import Navbar from './components/Navbar';
import Footer from './components/Footer';
import NavbarSmall from './components/NavbarSmall';
import { AuthProvider } from './context/AuthContext';
import { Livvic } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import { SearchProvider } from './context/SearchContext';
import Image from 'next/image';
import HamburgerMenu from './components/HamburgerMenu';

const livvic = Livvic({
  subsets: ["latin"],
  variable: "--font-livvic",
  weight: ["100", "400", "700"],
});

export const metadata: Metadata = {
  title: 'WonderWise',
  description: 'Generated by WonderWise',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" sizes='any' />  
      </head>
      <body
        className={`${livvic.variable} antialiased flex flex-col min-h-screen`}
      >
        <AuthProvider>
        <SearchProvider>
            <Toaster />
            <div className="hidden sm:block">
              <Navbar />
            </div>
            <div className="flex items-center justify-between sm:hidden px-4 py-2">
              <Image src="/images/Logo.png" alt="Logo" width={180} height={180} className="object-contain mx-auto my-4" />
              <HamburgerMenu />
            </div>
            <main>{children}</main>
            <div className="hidden sm:block">
              <Footer />
            </div>
            <div className="block sm:hidden">
              <NavbarSmall />
            </div>
            </SearchProvider>
        </AuthProvider>
      </body>
    </html>
  );
}